apiVersion: v1
kind: Secret
metadata:
  name: {{ include "businesswithoutwebsite.fullname" . }}-backend-secret
  namespace: {{ include "businesswithoutwebsite.namespace" . }}
  labels:
    {{- include "businesswithoutwebsite.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
