{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "businesswithoutwebsite.namespace" . }}
  labels:
    {{- include "businesswithoutwebsite.labels" . | nindent 4 }}
{{- end }}
