namespace: newb
createNamespace: false

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

frontend:
  replicaCount: 1
  image:
    repository: ikcloudky6/newbusiness
    tag: "frontend-latest"
    pullPolicy: Always
  containerPort: 80
  service:
    type: ClusterIP
    port: 80
  resources: {}
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

backend:
  replicaCount: 1
  image:
    repository: ikcloudky6/newbusiness
    tag: "backend-latest"
    pullPolicy: Always
  containerPort: 5000
  service:
    type: ClusterIP
    port: 5000
  env:
    PORT: "5000"
    CORS_ORIGIN: "http://100.93.86.88.nip.io"
  secretEnv:
    GOOGLE_PLACES_API_KEY: ""
    COMPANIES_HOUSE_API_KEY: ""
    BING_SEARCH_API_KEY: ""
  resources: {}
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

ingress:
  enabled: true
  className: tailscale
  annotations:
    tailscale.com/expose: "true"
  host: ""
  tls:
    enabled: false
    secretName: ""
